// const portfolio = [
//   {
//     id: 1,
//     title: 'Australien',
//     subTitle: 'Webseite',
//     desc: `Das Ziel des Projektes ist, die Menschen
//     mit dem Land kennenlernen und helfen dabei die richtigen Entscheidungen zu treffen.`,
//     image: './images/dest/australien3.png',
//     bgImage: './images/dest/australien-bg.png',
//     tech: ['css', 'html', 'js'],
//     website: 'https://australien.netlify.app/',
//     github: 'https://github.com/den777kaz/australien',
//   },
//   {
//     id: 2,
//     title: 'Fitness',
//     subTitle: 'Website',
//     desc: 'Mit dieser Webseite habe ich mit Bootstrap kennengelernt.',
//     image: './images/dest/fit-1.png',
//     bgImage: './images/dest/fit-as.png',
//     tech: ['html', 'sass', 'bootstrap 5'],
//     website: 'https://friendly-brattain-354084.netlify.app',
//     github: 'https://github.com/den777kaz/fitmotion',
//   },
//   {
//     id: 3,
//     title: 'Netflix',
//     subTitle: 'Web Application',
//     desc: 'Spaß und Übung!',
//     image: './images/dest/nitflex.png',
//     bgImage: './images/dest/nitflex.png',
//     tech: ['html', 'css', 'react', 'redux', 'restApi'],
//     website: 'https://nitflex.netlify.app/home',
//     github: 'https://github.com/den777kaz/netflix',
//   },
//   {
//     id: 2345,
//     title: 'Small Pizza Shop',
//     subTitle: 'Web Application',
//     desc: '',
//     image: './images/dest/react-pizza.png',
//     bgImage: './images/dest/react-pizza.png',
//     tech: ['React', 'Redux', 'Sass', 'json-server'],
//     website: 'https://shop-pizza.netlify.app',
//     github: 'https://github.com/den777kaz/react-pizza',
//   },
//   {
//     id: 4,
//     title: 'Pizzeria',
//     subTitle: 'Landing Page',
//     desc: `Das Ziel des Projektes ist es, das Image des Unternehmens weiter zu stärken und die Bekanntheit des Restaurant do Deni zu erhöhen und somit eine optimale Neukundengewinnung zu erzielen.
//     `,
//     image: './images/dest/pizzeria.png',
//     bgImage: './images/dest/pizza-bg.png',
//     tech: ['html', 'css', 'js', 'php'],
//     website: 'https://pizza-dodeni.netlify.app',
//     github: 'https://github.com/den777kaz/pizza',
//   },
// ];
